# Generated by Django 5.2.8 on 2025-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('MY', 'Malaysia'), ('SG', 'Singapore'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('LK', 'Sri Lanka'), ('KH', 'Cambodia'), ('LA', 'Laos'), ('MM', 'Myanmar'), ('BN', 'Brunei')], default='MY', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('buyer', 'Buyer'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
