from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProfileViewSet,
    WalletViewSet,
    ListingViewSet,
    OrderViewSet,
    MessageViewSet
)

# Create a router
# The router automatically generates the URLs for our ViewSets
router = DefaultRouter()

# Register our ViewSets with the router
# format: router.register(r'url-prefix', ViewSetClass, basename='basename')
router.register(r'profiles', ProfileViewSet, basename='profile')
router.register(r'wallets', WalletViewSet, basename='wallet')
router.register(r'listings', ListingViewSet, basename='listing')
router.register(r'orders', OrderViewSet, basename='order')
router.register(r'messages', MessageViewSet, basename='message')

# The API URLs are now determined automatically by the router.
# e.g., /api/listings/ will list all listings
# e.g., /api/listings/1/ will show detail for listing 1
urlpatterns = [
    # This includes all the URLs generated by the router
    path('', include(router.urls)),
]